BEGIN
delete FROM SYS_RSRC_CATALOG t WHERE t.id in (1,2,3,4,5,6,7,8);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(1,0,1,0,'SJ0001','设计类',1,2);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(2,0,2,0,'SD0002','水电工程类',1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(3,0,3,0,'NW0003','泥瓦工程类',1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(4,0,4,0,'MG0004','木工工程类',1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(5,0,5,0,'YQ0005','油漆工程类',1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(6,0,6,0,'SW0006','收尾工程类',1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(7,0,7,0,'ZQ0007','住前准备类',1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE)
values(8,0,8,0,'QT0008','其它类',1,1);
END;