BEGIN
delete FROM SYS_RSRC_CATALOG t WHERE t.id in (1,2,3,4,5,6,7,8,9);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(1,0,1,0,'1001','设计类',1,1,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(2,0,2,0,'2002','拆建工程类',1,2,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(3,0,3,0,'3003','水电工程类',1,3,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(4,0,4,0,'4004','泥瓦工程类',1,4,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(5,0,5,0,'5005','木工工程类',1,5,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(6,0,6,0,'6006','油漆工程类',1,6,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(7,0,7,0,'7007','收尾工程类',1,7,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(8,0,8,0,'8008','住前准备类',1,8,1);
insert into SYS_RSRC_CATALOG (id,row_version,ORDER_NO,PARENT_ID,CATALOG_CODE,CATALOG_NAME,CATALOG_STUTAS,CATALOG_TYPE,WORK_TYPE)
values(9,0,9,0,'9009','其它类',1,9,1);
END;